In [1]:
import pandas as pd
import pathlib

# 데이터 파일 경로 지정
root = pathlib.Path.cwd().parent.parent.parent
file_path       = root / "storage" / "raw" / "recipe" / "recipe.csv"
new_file_path   = root / "storage" / "processed" / "recipe" / "recipe_fix.csv" 

print(root)
print(new_file_path)

c:\dev\project\SKN27-FINAL-1Team
c:\dev\project\SKN27-FINAL-1Team\storage\processed\recipe\recipe_fix.csv

In [2]:
# 1차 수정된 파일 로드 
df = pd.read_csv(new_file_path)
df.head(1)

,RCP_SNO,CKG_NM,INQ_CNT,SRAP_CNT,CKG_MTH_ACTO_NM,CKG_STA_ACTO_NM,CKG_MTRL_ACTO_NM,CKG_KND_ACTO_NM,CKG_MTRL_CN,CKG_INBUN_NM,CKG_DODF_NM,CKG_TIME_NM
0,7037475,김장김치,60777,52,절임,일상,채소류,김치/젓갈/장류,"['절임배추_20_kg_(1상자 7~9포기)', ' 무_1_개_(1600g 채썰때 ...",6인분이상,중급,2시간이내

In [ ]:
# 조리법 개수 확인 
count = df["CKG_MTH_ACTO_NM"].nunique()
lst = df["CKG_MTH_ACTO_NM"].unique()

print(count)
print(lst)

14
['절임' '끓이기' '기타' '조림' '찜' '무침' '삶기' '볶음' '부침' '비빔' '굽기' '데치기' '튀김' '회' nan]

In [4]:
# 상황 개수 확인 
count = df["CKG_STA_ACTO_NM"].nunique()
lst = df["CKG_STA_ACTO_NM"].unique()

print(count)
print(lst)

13
['일상' '기타' '다이어트' '초스피드' '손님접대' '간식' '술안주' '야식' '명절' '영양식' nan '도시락' '해장'
 '이유식']

In [7]:
# 음식 분류 확인 
count = df["CKG_MTRL_ACTO_NM"].nunique()
lst = df["CKG_MTRL_ACTO_NM"].unique()

print(count)
print(lst)

16
['채소류' '닭고기' '기타' '과일류' '콩/견과류' '돼지고기' '가공식품류' '건어물류' '밀가루' '소고기' '곡류'
 '버섯류' '해물류' '달걀/유제품' '쌀' '육류']

In [8]:
# 음식 상세 분류 확인 
count = df["CKG_KND_ACTO_NM"].nunique()
lst = df["CKG_KND_ACTO_NM"].unique()

print(count)
print(lst)

17
['김치/젓갈/장류' '메인반찬' '밑반찬' '밥/죽/떡' '차/음료/술' '찌개' '국/탕' '양식' '면/만두' '양념/소스/잼'
 '과자' '기타' '디저트' '스프' '퓨전' '샐러드' '빵']

In [9]:
df.head(1)

,RCP_SNO,CKG_NM,INQ_CNT,SRAP_CNT,CKG_MTH_ACTO_NM,CKG_STA_ACTO_NM,CKG_MTRL_ACTO_NM,CKG_KND_ACTO_NM,CKG_MTRL_CN,CKG_INBUN_NM,CKG_DODF_NM,CKG_TIME_NM
0,7037475,김장김치,60777,52,절임,일상,채소류,김치/젓갈/장류,"['절임배추_20_kg_(1상자 7~9포기)', ' 무_1_개_(1600g 채썰때 ...",6인분이상,중급,2시간이내

In [11]:
# 분량 확인 
count = df["CKG_INBUN_NM"].nunique()
lst = df["CKG_INBUN_NM"].unique()

print(count)
print(lst)

6
['6인분이상' '2인분' '1인분' nan '3인분' '4인분' '5인분']

In [12]:
# 난이도 확인 
count = df["CKG_DODF_NM"].nunique()
lst = df["CKG_DODF_NM"].unique()

print(count)
print(lst)

4
['중급' '아무나' '초급' '고급']

In [13]:
# 조리 시간 
count = df["CKG_TIME_NM"].nunique()
lst = df["CKG_TIME_NM"].unique()

print(count)
print(lst)

8
['2시간이내' '60분이내' '2시간이상' '30분이내' nan '10분이내' '15분이내' '5분이내' '90분이내']